### PR TITLE
Allowed wildcard for subdomains of incrementally.xyz

### PR DESCRIPTION
**Pull request by stianlaa**
I think this should work well as origin from Incrementally is for example:
https://www.incrementally.xyz/explore
(Note that www is seen as a subdomain here)

/explore and various id's should not affect CORS, according to microsofts azure cors doc.
https://docs.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-3.1#testc

### CODE REVIEW

**Comment by holwech** [comment]
This is wildcards for sub-domains, e.g. test.incrementally.com. What we would need is a wildcard at the end, for example: "incrementally.xyz/*". I think there are security issues with this approach, which is why ASP.NET does not allow you to do it. See related: https://joonasw.net/view/avoiding-wildcard-reply-urls-with-msal-js

**Comment by holwech** [comment]
Actually wildcards might not be necessary, as just including the base URL might allow for all sub-URLs? Including "incrementally.xyz/editor" might be redundant?

Since "/explorer" seems to be working without it being included in the list, that might be the case?

**Comment by stianlaa** [comment]
According to the initial documentation I sited the following two urls would be seen as coming from the same origin:

https://example.com/foo.html
https://example.com/bar.html

which is why I claim that we would **not** need a wildcard at the end. The cors issue we are encountering is I suspect due to our origin being https://www.incrementally.xyz/explore, emphasis on **www** being part of the sub-domain. The reason I went for allowing the wildcard within our domain is because I view all routing from the .incrementally domain as trusted.

Note that I do agree with your link aswell, that we should avoid wildcards where possible.

**Comment by holwech** [comment]
[AB#14](https://dev.azure.com/incrementally/6e119c52-39a8-4798-85c7-142aed46bee9/_workitems/edit/14)

**Pull request merged**
